name: Update Issue on New Discussion Comment

on:
  discussion_comment:
    types: [created]

jobs:
  update-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Update issue on new comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: node update-issue.js
